name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install git-secrets
        run: |
          git clone --depth 1 https://github.com/awslabs/git-secrets
          cd git-secrets
          git checkout b9e96b3212fa06aea65964ff0d5cda84ce935f38
          sudo make install

      # ref: https://github.com/pre-commit/action
      # Run "pre-commit run --all-files"
      - uses: pre-commit/action@v2.0.3
